services:
  storage:
    image: postgres:alpine3.19 
    restart: always
    ports: 
      - 5050:5432
    volumes:
      - storage:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: snippetbox
      POSTGRES_USER: snippetbox
      POSTGRES_PASSWORD: snippetbox
volumes:
  storage: 
